package gui;

import javafx.application.Application;

/**
 * Starts the maze application.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public class Launcher
{
    /**
     * Entry point to the application.
     * @param args the command-line arguments (not used)
     */
    public static void main(String[] args)
    {
        Application.launch(MazeUICompleted.class);
    }
}
